package lightwave // generated by gen

import "core:testing"
import ot "shared:ounit"

@(test)
verify_struct_sizes :: proc(t: ^testing.T) {
	using ot
	expect_size(t, lwNode, 24)
	expect_size(t, lwPlugin, 48)
	expect_size(t, lwKey, 56)
	expect_size(t, lwEnvelope, 72)
	expect_size(t, lwEParam, 8)
	expect_size(t, lwVParam, 16)
	expect_size(t, lwClipStill, 8)
	expect_size(t, lwClipSeq, 40)
	expect_size(t, lwClipAnim, 24)
	expect_size(t, lwClipXRef, 24)
	expect_size(t, lwClipCycle, 16)
	expect_size(t, lwClip, 152)
	expect_size(t, lwTMap, 88)
	expect_size(t, lwImageMap, 72)
	expect_size(t, lwProcedural, 32)
	expect_size(t, lwGradKey, 40)
	expect_size(t, lwGradient, 48)
	expect_size(t, lwTexture, 208)
	expect_size(t, lwTParam, 16)
	expect_size(t, lwCParam, 24)
	expect_size(t, Glow, 20)
	expect_size(t, lwRMap, 32)
	expect_size(t, lwLine, 12)
	expect_size(t, lwSurface, 320)
	expect_size(t, lwVMap, 64)
	expect_size(t, lwVMapPt, 16)
	expect_size(t, lwPoint, 40)
	expect_size(t, lwPolVert, 32)
	expect_size(t, lwPolygon, 48)
	expect_size(t, lwPointList, 16)
	expect_size(t, lwPolygonList, 24)
	expect_size(t, lwLayer, 128)
	expect_size(t, lwTagList, 16)
	expect_size(t, lwObject, 64)
}
