package test_lightwave // generated by gen

import "core:testing"
import ot "shared:ounit"
import lw ".."

@(test)
verify_struct_sizes :: proc(t: ^testing.T) {
	using ot
	expect_size(t, lw.lwNode, 24)
	expect_size(t, lw.lwPlugin, 48)
	expect_size(t, lw.lwKey, 56)
	expect_size(t, lw.lwEnvelope, 72)
	expect_size(t, lw.lwEParam, 8)
	expect_size(t, lw.lwVParam, 16)
	expect_size(t, lw.lwClipStill, 8)
	expect_size(t, lw.lwClipSeq, 40)
	expect_size(t, lw.lwClipAnim, 24)
	expect_size(t, lw.lwClipXRef, 24)
	expect_size(t, lw.lwClipCycle, 16)
	expect_size(t, lw.lwClip, 152)
	expect_size(t, lw.lwTMap, 88)
	expect_size(t, lw.lwImageMap, 72)
	expect_size(t, lw.lwProcedural, 32)
	expect_size(t, lw.lwGradKey, 40)
	expect_size(t, lw.lwGradient, 48)
	expect_size(t, lw.lwTexture, 208)
	expect_size(t, lw.lwTParam, 16)
	expect_size(t, lw.lwCParam, 24)
	expect_size(t, lw.Glow, 20)
	expect_size(t, lw.lwRMap, 32)
	expect_size(t, lw.lwLine, 12)
	expect_size(t, lw.lwSurface, 320)
	expect_size(t, lw.lwVMap, 64)
	expect_size(t, lw.lwVMapPt, 16)
	expect_size(t, lw.lwPoint, 40)
	expect_size(t, lw.lwPolVert, 32)
	expect_size(t, lw.lwPolygon, 48)
	expect_size(t, lw.lwPointList, 16)
	expect_size(t, lw.lwPolygonList, 24)
	expect_size(t, lw.lwLayer, 128)
	expect_size(t, lw.lwTagList, 16)
	expect_size(t, lw.lwObject, 64)
}
